# Generated by Django 5.2 on 2025-04-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('social-media', 'Social Media'), ('e-commerce', 'E-commerce'), ('personal', 'Personal')], max_length=20, unique=True)),
                ('last_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_recovered_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
